### PR TITLE
Added a copy button to copy the conversions

### PR DESCRIPTION
**Pull request by anubhav1206**

### CODE REVIEW

**Comment by bitkarrot** [comment]
Hi thanks for the pull request, unfortunately the copy button doesn't copy the rate to the clipboard. 

also the formatting is misaligned. perhaps it would be better if grid were reformatted so that the buttons are aligned better on wide screen. the fiat currency button (HKD) is cut off and not viewable

Screenshot 2023-04-28 at 6 09 35 PM


there should not be "python install" commands at the top of the index page. 

Screenshot 2023-04-28 at 6 10 16 PM

**Comment by bitkarrot** [comment]
here is an example of what we are aiming for. It should look good on big screen and also on small mobile.
https://xsats.net/SAT/USD/

**Comment by anubhav1206** [comment]
Noted. I will try to work it out.

**Comment by bitkarrot** [comment]
are you still working on this issue? as someone else has also started working on it. If not, I will close this PR in the next day. thanks

**Comment by anubhav1206** [comment]
I am no longer working on it

**Pull request closed without merging**
