### PR TITLE
implemented BTC/SATS toggle button

### PR DESCRIPTION
**Pull request by charanravi-online**
Firstly, added a toggle button which toggles between BTC and SATS.
Next, added an if statement which check what the state of the button is (whether BTC or SATS) and implements the logic/script accordingly.

### CODE REVIEW

**Comment by bitkarrot** [comment]
Hi @charanravi-online thanks for submitting this pr!

A few things: 
- When clicking the BTC button to convert to Sats, the rest of the data on the page does not adjust, in the form box, if I click sats, the form values on the fiat side should update, and vice versa when clicking on 'sats' -> btc, the fiat field should also update. In the image below it says 1 sat == 27, 182.21 usd, which is the 1 btc value. 
Suggestion: Perhaps a higher starting value for sats should be used such as 1000 Sats and then the corresponding fiat value in the form box as it is very small 
 
Screenshot 2023-05-14 at 7 50 57 PM

- 
- When the page is on Sats option, the orange text below should be displaying btc units, instead of sats

Screenshot 2023-05-14 at 7 52 07 PM


-  The sats option should be the default option when arriving at the main page, but lets try to fix the above items first before doing this

**Comment by charanravi-online** [comment]
The input values are set to clear when BTC/SATS button is toggled (similar to when FIAT options are changed).
This would alllow the user to enter sats and btc values and the results would update accordingly and not cause confusion like the previous commit.

**Comment by bitkarrot** [comment]
Ok, I checked the "clearing" option, which works on the preview deploy

two items remain: 

1.  Sats option should be the default setting first, instead of btc
2. When the user has enabled sats option, the yellow text below should be btc units, not sats, as mentioned above in [image](https://user-images.githubusercontent.com/73979971/238231834-d92501b1-11ba-4fd6-8536-ac21a321bea5.png)

**Comment by charanravi-online** [comment]
> Sats option should be the default setting first, instead of btc

this should make the SATS option the default.

**Comment by charanravi-online** [comment]
This should solve all of the mentioned points
1. Clearing option to avoid confusion when using switching between BTC and SATS.
2. SATS option is set as the default option.
3. When user toggles between SATS & BTC options on the button, the yellow text also changes according to the Button state displaying SATS when button is set to BTC and displays BTC when button is set to SATS.

@bitkarrot requesting your review.

**Comment by bitkarrot** [comment]
Hi @charanravi-online  I see some errors during conversion, see the images below. The other conversions appear ok. 

Also is possible when clicking on Sats -> Btc to be able to keep the form values instead of making blank? 

Screenshot 2023-06-12 at 11 52 42 PM

Screenshot 2023-06-12 at 11 52 18 PM
Screenshot 2023-06-12 at 11 52 00 PM
Screenshot 2023-06-12 at 11 48 12 PM

**Comment by bitkarrot** [comment]
How's the update going? @charanravi-online

**Comment by bitkarrot** [comment]
@charanravi-online please pull from main to get latest updates from merge. thanks

**Comment by bitkarrot** [comment]
@ssingampalli, Charan (@charanravi-online) mentioned he is stuck on this issue and could use some help looking at the bug. If you are interested in taking a look, feel free to check out the branch.

**Comment by bitkarrot** [comment]
@charanravi-online as there's been no activity since June.
Please let us know otherwise if you are still working on this PR. 

If not, we will close it in the next week.

**Comment by charanravi-online** [comment]
@bitkarrot I appreciate the update on the PR. I've been facing challenges in resolving the errors, and despite my efforts, it's taking more time than anticipated. I understand the need to close it, so if that's the decision, I'm okay with it.

**Comment by bitkarrot** [comment]
@charanravi-online this repo is no longer being updated, the latest version has been cloned and maintained independently here: https://github.com/plebnet-dev/rates, I believe we resolved the issue over there. 

whenever you feel like coming back to the group, you are welcome.

**Comment by bitkarrot** [comment]
@charanravi-online you can see how this issue is solve in the new repository https://github.com/plebnet-dev/rates

**Pull request closed without merging**
