### PR TITLE
Copy button for converter

### PR DESCRIPTION
**Pull request by arthurfary**
Added the copy button for the converter:

image

A new function called `copyToClipboard(id)` was added, you can add more copy buttons if you want, just call the function passing the input's id as the parameter. For now the function creates an alert telling the user that it has been copied!
image

Added the svg also, it can be changed too, just put another svg with the same name!

### CODE REVIEW

**Comment by bitkarrot** [comment]
Hi, thanks for the PR, the copy method works,  however on mobile the formatting is not quite good. here are some screenshots  that show the layout for smaller screens could be improved. Perhaps adjusting the grid to make it fit better?  Or balance it out by adding a copy button on both the btc and the fiat form box? 
 
Screenshot 2023-04-30 at 11 15 59 PM

Screenshot 2023-04-30 at 11 15 01 PM

Screenshot 2023-04-30 at 11 15 22 PM

**Comment by arthurfary** [comment]
I've been tinkering with it for some time now and I cant make it look good in PICO css (I can make it look good on mobile and desktop separately, but not together), would you consider switching over to bootstrap?

**Comment by bitkarrot** [comment]
> I've been tinkering with it for some time now and I cant make it look good in PICO css (I can make it look good on mobile and desktop separately, but not together), would you consider switching over to bootstrap?

We'd like to keep Pico css. Perhaps its the grid system. I believe there is a way to extend pico using boostrap and the corresponding css grid system on their docs somewhere. https://picocss.com/docs/

**Comment by bitkarrot** [comment]
@arthurfary  - definitely check out the grid page - there's a whole section on how to integrate bootstrap at the bottom https://picocss.com/docs/grid.html

**Comment by arthurfary** [comment]
Will do, Thank you for the help!

**Comment by bitkarrot** [comment]
@arthurfary are you still working on this issue?

**Comment by arthurfary** [comment]
I'm sorry, I got caught up in other projects and completely forgot about this one. I need to finish some other stuff first.
You want, I gave you permission to copy all of the code that I've written and alter it the way you see fit. I'll need about a week to get back to it if you want to wait.

**Comment by bitkarrot** [comment]
@arthurfary sure, no rush here, we'll wait. Thanks for letting us know you're still working on it.

**Comment by bitkarrot** [comment]
Closing this PR since there has been no activity in the last few weeks. If you are still interested in working on it, please open a new PR. This task is now free for another developer to take it. thank you.

**Pull request closed without merging**
